config/routes.rb
Rails.application.routes.draw do
  get '/agreement' => 'home#agreement'

  # root 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts/create' => 'posts#create'
  post 'posts/:random_key/destroy' => 'posts#destroy'
  post 'posts/:random_key/check' => 'posts#check_answer'
  get 'posts/:random_key' => 'posts#show'

  post 'comments/:random_key/create' => 'comments#create'

  get 'users/:nickname/edit' => 'users#edit'
  patch 'users/:nickname/update' => 'users#update'
  root 'users#new'
  post 'users/create/:auth' => 'users#create'
  get 'users/:nickname' => 'users#show'
  get '/auth/:provider/callback' => 'users#create'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, length:{maximum: 100}
	validates :question, length:{maximum: 150}
	validates :answer, length:{maximum: 30}
	validates :check_count, :user_id, presence: true
	validate :add_presence_errors
	validates :random_key, uniqueness: {message: '投稿してください。'}
	has_many :answer_histories, dependent: :destroy
	belongs_to :user

	def add_presence_errors
		if question.empty?
			errors.add(:question, "を出して友達を厳選しよう！")
		elsif answer.empty?
			errors.add(:answer, "がわからないよ...")
		elsif count.blank?
			errors.add(:count, "が選択されていないよ...")
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :post_params, {only:[:create]}
  before_action :brock_not_current_user, {only:[:new, :create, :destroy]}
  before_action :find_post, {only:[:show, :destroy, :check_answer, :brock_not_post_user]}
  before_action :find_answerer, {only:[:show, :check_answer]}
  before_action :brock_not_post_user, {only:[:destroy]}

  # def index
  # 	@posts = Post.page(params[:page]).per(15).order(created_at: "DESC")
  #   @comment = Comment.new
  #  redirect_to '/'
  # end

  def show
  	@user = User.find(@post.user_id)
    @comments = Comment.where(post_id: @post.id).order(created_at: 'DESC')
    @comment = Comment.new
    @answerers = AnswerHistory.where(post_id: @post.id).order(number: 'ASC')
    if @answerer || @current_user && @current_user.id == @post.user_id || session[:correct_user] == @post.id
      return
    else
      # ログインユーザーがAnswerHistoryに載っていないか、投稿主idとログインユーザが一致しなければリダイレクト。
      flash[:notice] = "問題に答えてください。"
      redirect_to "/users/#{@user.nickname}"
    end
  end

  def new
    @random = SecureRandom.urlsafe_base64
  	@post = Post.new
    @question_samples = [
      {'name' => '誕生日', 'text' => 'わたしの誕生日は？'},
      {'name' => '好きな人', 'text' => 'わたしの好きな人は？'},
      {'name' => '趣味', 'text' => 'わたしの趣味は？'},
      {'name' => '武勇伝', 'text' => 'わたしの武勇伝は？'},
      {'name' => '歌手', 'text' => 'わたしの好きな歌手は？'},
      {'name' => 'スポーツ', 'text' => 'わたしの尊敬するスポーツ選手は？'},
      {'name' => '座右の銘', 'text' => 'わたしの座右の銘は？'},
      {'name' => '好み', 'text' => 'わたしの好みのタイプは？'},
      {'name' => '食べ物', 'text' => 'わたしの好きな食べ物は？'}
    ]
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
      @user = User.find(@post.user_id)
      session[:new_post] = @post.id
  		flash[:notice] = '投稿しました。'
  		redirect_to "/users/#{@user.nickname}"
  	else
  		render 'posts/new'
  	end
  end

  def destroy
    user = User.find(@post.user_id)
    if @post
      @post.destroy
      redirect_to "/users/#{user.nickname}", notice: "削除しました。"
    else
      redirect_to '/users/#{user.nickname}', notice: "エラーが発生しました。"
    end
  end

  def check_answer
    user_answer = params[:answer]
    user = User.find(@post.user_id)
    @answer_history = AnswerHistory.find_by(user_id: @current_user.id, post_id: @post.id) if @current_user
      # 公開人数と問題に正解した人の数を比較
    if @post.check_count < @post.count
        # 答えがあっていればパス
      if @post.answer == user_answer
          # ログインユーザーかつログインユーザーと回答ユーザーのidが違うならパス。
        if !@current_user || @current_user.id != user.id
          @post.check_count += 1
          @post.save
          # 条件によってAnswerHistoryに保存する方法を変更する
          correct_answer_history_save(@answer_history, @post, @current_user)
          # 正常に処理が終わったらここで終了
          redirect_to "/posts/#{@post.random_key}", notice: '正解です！！'
          return
        else
          flash[:notice] = '無効な回答です。'
          redirect_to "/users/#{user.nickname}"
        end
      else
        flash[:notice] = '不正解です！！'
        if @current_user && !@answer_history
          @history = AnswerHistory.new(user_id: @current_user.id, post_id: @post.id, number: @post.check_count, check: false)
          @history.save
        elsif @current_user && @answer_history
          flash[:notice] = '不正解です！よく考えて！'
        elsif !@current_user
          @history = AnswerHistory.new(post_id: @post.id, number: @post.check_count, check: false)
          @history.save
        end
        # 不正解のとき回答したユーザー問題ページへ遷移
        redirect_to "/users/#{user.nickname}"
      end
    else
      redirect_to "/users/#{user.nickname}", notice: '定員に達しました。'
    end
  end

  def brock_not_post_user
    user = User.find(@post.user_id)
    redirect_to "/users/#{user.nickname}", notice: "権限がありません。" if user.id != @current_user.id
  end

  private
   def post_params
   	 params.require('post').permit(:body, :user_id, :question, :answer, :count, :check_count, :random_key)
   end

   def find_post
     @post = Post.find_by(random_key: params[:random_key])
   end

   def find_answerer
     @answerer = AnswerHistory.find_by(user_id: @current_user.id, post_id: @post.id) if @current_user
   end

   def correct_answer_history_save(history, post, user)
    if user && history
      # すでにユーザーが回答していて、不正解のため履歴に残っていた場合trueを代入して正解判定にする。
      history.check = true
      history.number = post.check_count
      history.save
    elsif user && !history
      new_history = AnswerHistory.new(user_id: user.id, post_id: post.id, number: post.check_count, check: true)
      new_history.save
    elsif !user
      # ユーザーがログインしていない場合user_idに0を代入する
      new_history = AnswerHistory.new(user_id: 0, post_id: post.id, number: post.check_count, check: true)
      new_history.save
      session[:correct_user] = post.id
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.slim
- @posts.each do |post|
  - @user = User.find(post.user_id)
  - if post.count > post.check_count
    - @answerer = AnswerHistory.find_by(user_id: @current_user.id, post_id: post.id, check: true) if @current_user
    - if @answerer || @current_user && @current_user.id == post.user_id || session[:correct_user] == post.id
      .post
        = link_to "/posts/#{post.id}", class: "border-none" do
          .post-contents
            p.post-question = html_escape(post.question).gsub(/\n/, '<br>').html_safe
          p.post-count
           = post.check_count
           | /
           = post.count
           | 人が正解
          .clear-right
        .post-menu
          .post-username
            - if !@user.image.blank?
              = image_tag @user.image, class: 'post-user-img'
            - elsif !@user.icon_url.blank?
              = image_tag @user.icon_url, class: 'post-user-img'
            - else
              p.post-user-noimg = @user.username[0]
            p.post-user = link_to @user.username, "/users/#{@user.nickname}", class: 'border-none btn-black'
          .clear-left
          p.post-time = simple_time(post.created_at)
          .clear-right
    - else
      .post
        .post-box data-id="#{post.id}" data-question="#{post.question}"
          .post-contents
            p.post-question = html_escape(post.question).gsub(/\n/, '<br>').html_safe
          p.post-count
           = post.check_count
           | /
           = post.count
           | 人が正解
          .clear-right
        .post-menu
          .post-username
            - if !@user.image.blank?
              = image_tag @user.image, class: 'post-user-img'
            - elsif !@user.icon_url.blank?
              = image_tag @user.icon_url, class: 'post-user-img'
            - else
              p.post-user-noimg = @user.username[0]
            p.post-user = link_to @user.username, "/users/#{@user.nickname}", class: 'border-none btn-black'
          .clear-left
          p.post-time = simple_time(post.created_at)
          .clear-right

app/views/posts/_post_form.html.slim
.form
  .error
    - @post.errors.full_messages.each do |message|
      p = message
  = form_for @post, url: posts_create_path do |f|
    .form-area
      label for="post_question" class="user-label"
       i.fa.fa-quora
       |  問題(150文字まで)
      .question-sample
        - @question_samples.each do |sample|
          p.question-sample-text data-question_text="#{sample['text']}" = sample['name']
      = f.text_area :question, placeholder: '友達だけが知っていることは？（例：ABC君の誕生日は？）※上のボタンを押すと簡単に問題を作れるよ！', maxlength: 150, rows: 8, id: "question-text"
      label for="post_answer" class="user-label"
       i.fa.fa-unlock-alt
       |  答え(30文字まで)
      = f.text_area :answer, placeholder: '問題の答えは？（例：5月10日）', maxlength: 30, rows: 3
      label for="post_count" class="user-label"
       i.fa.fa-group
       |  公開人数
      br
      = f.select :count, [['3人', 3],['5人', 5],['8人', 8],['10人', 10]]
      = f.hidden_field :check_count, value: 0
      = f.hidden_field :random_key, value: "#{@random}"
  	  = f.hidden_field :user_id, value: @current_user.id
      br
      label for="post_body" class="user-label"
       i.fa.fa-key
       |  秘密・思い(100文字まで)※任意
      = f.text_area :body, placeholder: '正解した人に伝えたいことがあれば入力してください！', maxlength: 100, rows: 3

  	  = f.submit value: 'つぶやく', data: { disable_with: "作成中..." }, class: 'button-simple'

app/views/posts/index.html.slim
.post-page
  = render partial: 'post'
  = paginate @posts

- if !@current_user
  .foot-space

app/views/posts/new.html.slim
.post-page
  = render partial: 'post_form'

app/views/posts/show.html.slim
.post-page
  - if !@post.body.blank?
    .post-show
      .post-contents
        p.post-body = html_escape(@post.body).gsub(/\n/, '<br>').html_safe
      .post-menu
        - if !@user.image.blank?
          = image_tag @user.image, class: 'post-user-img'
        - elsif !@user.icon_url.blank?
          = image_tag @user.icon_url, class: 'post-user-img'
        - else
          p.post-user-noimg = @user.username[0]
        p.post-user = link_to @user.username, "/users/#{@user.nickname}", class: "border-none btn-black"
        p.post-time = simple_time(@post.created_at)
        .clear-right.clear-left
  .post-comment
    h3.post-comment-title メッセージ
    #post-comment-lists
      = render partial: 'comments/comment'
    = form_for @comment, url: "/comments/#{@post.random_key}/create", remote: true do |f|
      .comment-form
        = f.text_area :body, placeholder: "#{@user.username}にメッセージを飛ばしてみよう！", maxlength: 150, rows: 8, id: "comment-text"
        - if @current_user
          = f.hidden_field :user_id, value: @current_user.id
        - else
          = f.hidden_field :user_id, value: 0
        = f.hidden_field :post_id, value: @post.id
        br
        = f.submit value: 'メッセージを送る', data: { disable_with: "送信中..." }, class: 'button-simple', id: "comment-btn"
        .clear-right
  .answerer-list
    h3.answerer-title あなたをよく知る人
    - ranking = 0
    - @answerers.each do |answerer|
      - ranking += 1
      .answerer
        - if answerer.user_id.to_i == 0
          - username = guest_name_change(answerer.number)
          - user_image = ""
          - user_icon = ""
          - user_url = "#"
        - else
          - @user = User.find(answerer.user_id)
          - username = @user.username
          - user_image = @user.image
          - user_icon = @user.icon_url
          - user_url = "/users/#{@user.nickname}"
        = link_to user_url, class: "border-none" do
          .answerer-user
            - if !user_image.blank?
              = image_tag user_image, class: 'answerer-img'
            - elsif !user_icon.blank?
              = image_tag user_icon, class: 'answer-img'
            - else
              h3.answerer-noimg = username[0]
            h3.answerer-name = username
          .clear-left
        .answerer-menu
          p.answerer-rank
           | 第
           = ranking
           | 位
          .clear-left
          p.answerer-time = simple_time(answerer.created_at)
    - if @answerers.blank?
        p.no-answer-notice
         | まだ正解者がいません。
         br
         | ツイートしてみよう！
- if !@current_user
  .footer-space